/**
 * User Schema
 *
 * Lightweight user profile. Authentication and session management are handled
 * externally by Authelia (forward-auth via nginx). The app receives the
 * authenticated identity via trusted proxy headers (Remote-User, Remote-Name,
 * Remote-Groups) and stores minimal profile information for ownership and ACL
 * purposes. Users are provisioned just-in-time on first authenticated request.
 */

import { z } from 'zod';

/** Core user schema — no passwords, no global role */
export const UserSchema = z.object({
  /** Unique internal identifier (generated by this app) */
  id: z.string().min(1),
  /** Email address, sourced from Remote-User header — unique */
  email: z.string().email(),
  /** Display name, sourced from Remote-Name header */
  name: z.string().min(1).max(100),
  /** Account creation timestamp */
  createdAt: z.string().datetime(),
  /** Last update timestamp */
  updatedAt: z.string().datetime(),
  /** Whether the account is active */
  active: z.boolean().default(true),
  /**
   * Optional identifier from the external identity provider (e.g. Authelia
   * username) if it differs from the email. Stored for audit purposes only.
   */
  externalId: z.string().optional(),
});

export type User = z.infer<typeof UserSchema>;

/**
 * The user object as seen at runtime — includes groups injected per-request
 * from the Remote-Groups header (not persisted to disk).
 */
export const RuntimeUserSchema = UserSchema.extend({
  /** Groups from the Remote-Groups header — used for admin override checks */
  groups: z.array(z.string()).default([]),
});

export type RuntimeUser = z.infer<typeof RuntimeUserSchema>;

// PublicUser is identical to RuntimeUser — kept for API compatibility
export type PublicUser = RuntimeUser;
